name: object_detection_flutter
description: A high-performance Flutter package for real-time, multi-model (object detection, classification, pose, face, YOLOv5) vision tasks using TensorFlow Lite with isolate support.
version: 0.1.0 # Start with a pre-release version like 0.1.0 or 1.0.0-beta.1 if you prefer
homepage: https://github.com/7awy11/object_detection_flutter
repository: https://github.com/7awy11/object_detection_flutter
issue_tracker: https://github.com/7awy11/object_detection_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0" 
dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0 
  image: ^4.1.7
  path_provider: ^2.1.2 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# Flutter specific section
flutter:
  # Packages that publish assets as part of their API should generally NOT include
  # them in the package's own assets section unless they are truly fundamental
  # examples FOR THE PACKAGE ITSELF, not for end-users to directly depend on.
  # Users of your package will add THEIR OWN model.tflite and labels.txt to THEIR app's assets.
  # assets:
  #   - assets/ # If you have example assets for documentation, maybe, but generally not for the package API.